### ISSUE TITLE
a little suggestion

### ISSUE THREAD

**Issue by zqy767** [sharplispers/cl-jpeg#28]
As we can see, there is no dct library written by common lisp. So if you can offer some inferface about dct, this project will be used more widely.

**Comment by varjagg** [comment]
Sounds like a good idea, but this implementation has only one (I)DCT method optimized for fixed block size of 8x8. I'm not sure how common is this outside of JPEG domain. Otherwise factoring it out into a subsystem could be possible.

**Comment by zqy767** [comment]
I think it will be useful. Now I was doing Information hiding, but there is no dct library. the only thing I can do is (in-package :cl-jpeg) and use your code :-）

**Comment by varjagg** [comment]
I exported LLM-DCT and INVERSE-LLM-DCT from the package now to those who use them, but not any kind of DCT API at the moment.
