### ISSUE TITLE
Expose decode-frame and friends

### ISSUE THREAD

**Issue by slyrus** [sharplispers/cl-jpeg#29]
My retrosspectiff package uses cl-jepg for decoding jpeg-encoded TIFF images. These images have the jpeg-tables info split up from the frame info, so I can't just call decode-stream on them. It would be nice if there were stable, exported interfaces I could use instead of having to do: 

```
(defvar *jpeg-stream*)

(defun jpeg-stream-reader ()
  (read-byte *jpeg-stream*))

(defun read-jpeg-tables (jpeg-image-info)
  (let* ((*jpeg-stream* (flexi-streams:make-in-memory-input-stream
                         (jpeg-tables jpeg-image-info))))
    (let ((image (jpeg::make-descriptor
                  :byte-reader #'jpeg-stream-reader)))
      (unless (= (jpeg::read-marker image) jpeg::+M_SOI+)
        (error "Unrecognized JPEG format"))
      (let ((marker (jpeg::interpret-markers image 0)))
        (unless (= marker jpeg::+M_EOI+)
          (error "Unrecognized JPEG format")))
      (setf (jpeg-image jpeg-image-info) image))))

(defun jpeg-decode (compressed-vector jpeg-image-info)
  ;;  NOTE: we currently read the jpeg-tables every time through. We
  ;;  should be able to cache this, but we don't as its state gets
  ;;  modified by the JPEG reading stuff and we can't just reuse it
  ;;  each time through. So..., for the moment at least, we make a new
  ;;  one each time through.
  (read-jpeg-tables jpeg-image-info)
  (let ((image (jpeg-image jpeg-image-info)))
    (let ((*jpeg-stream* (flexi-streams:make-in-memory-input-stream compressed-vector)))
      (unless (= (jpeg::read-marker image) jpeg::+M_SOI+)
        (error "Unrecognized JPEG format"))
      (let* ((marker (jpeg::interpret-markers image 0)))
        (cond ((= jpeg::+M_SOF0+ marker)
               (jpeg::decode-frame image nil)
               (jpeg::descriptor-buffer image))
              (t (error "Unsupported JPEG format: ~A" marker)))))))
```

**Comment by varjagg** [comment]
There is a :descriptor option to decoder, used by e.g. cl-video to supply DHT which is same for whole AVI file: https://github.com/varjagg/cl-video/blob/master/avi.lisp#L142

Does that help?

**Comment by slyrus** [comment]
It's possibly that could help, but that's still using the unexported interface of jpeg::make-descriptor (and (setf (jpeg::descriptor-byte-reader ...))). I think I might be able to make things work using the descriptor, but the interface for making/setting that should be exported.

**Comment by varjagg** [comment]
OK I now exported make-descriptor and descriptor-byte-reader. Question is if there is a better abstraction for all that, but it really hinges on typical use cases, and we have only two right now. Either way it's probably better than exposing random bits of control flow that weren't meant to be API surface.
