### ISSUE TITLE
update README etc... to reflect the canonical source location

### ISSUE THREAD

**Issue by slyrus** [sharplispers/cl-jpeg#34]
Is this now the preferred home for the source? Should we remove the text about this being a mirror? Should we update the cl-user.net page?

**Comment by varjagg** [comment]
I agree, the repo caption should just say 'Common Lisp JPEG Library' or something. I could add the link back in README.md but can't edit the repo caption.

**Comment by varjagg** [comment]
OK I fixed the README for now. BTW would be great if you could add a line about your last PR into the ChangeLog.

**Comment by slyrus** [comment]
Should we keep the cl-user.net link or remove it?

**Comment by varjagg** [comment]
IMO we can well remove it.

**Comment by slyrus** [comment]
Done.
