### ISSUE TITLE
Build failure with SBCL SBCL 1.3.0.162-37e9044

### ISSUE THREAD

**Issue by varjagg** [sharplispers/cl-jpeg#8]
Looking into this:

http://report.quicklisp.org/2015-11-16/failure-report/cl-jpeg.html#cl-jpeg

**Comment by varjagg** [comment]
@xach it loads for me, what was the command that generated it?

**Comment by xach** [comment]
Try (ql:quickload "cl-jpeg" :verbose t)?

**Comment by varjagg** [comment]
see pull request #9
